main_task:
  container:
    image: rust:latest
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  env:
    matrix:
      - ETHOX_FEATURES:
      - ETHOX_FEATURES: alloc
      - ETHOX_FEATURES: std
      - ETHOX_FEATURES: sys
      - ETHOX_FEATURES: alloc sys
      - ETHOX_FEATURES: std sys
  build_script: cargo build --no-default-features --features "$ETHOX_FEATURES"
  test_script: cargo test --no-default-features --features "$ETHOX_FEATURES"
  before_cache_script: rm -rf $CARGO_HOME/registry/index

nightly_task:
  container:
    image: rustlang/rust:nightly
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  build_script: cargo build --all-features
  test_script: cargo test --all-features
  before_cache_script: rm -rf $CARGO_HOME/registry/index

doc_task:
  container:
    image: rustlang/rust:nightly
  script: cargo doc --no-deps --document-private-items --all-features
