[workspace]
members = [
	"ethox",
	"ethox-iperf3",
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
# We should properly handle every issue with errors.
# This reduces compiled size.
panic = "abort"
